[package]
name = "time-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-backtrace = "0.12.0"
esp-hal = "0.21.1"
esp-println = "0.8.0"
esp-wifi = { version = "0.10.1", features = ["wifi"] }
martos = { path = "../../../../", features = ["network"] }
